'use client'
import { makeStyles } from "@griffel/react"

export const useStyle = makeStyles({
    page: {
        display: 'flex',
        flexDirection: 'column',
        background: 'white',
        minHeight: '100vh',
    },
    body: {
        flex: 1,
        display: 'flex',
        flexDirection: 'column',
        gap: '2.5rem',
        padding: '0 0 2.5rem 0',
        width: '100%',
        alignItems: 'center',
    },
    heroSection: {
        width: '100%',
        display: 'flex',
        flexDirection: 'column',
        alignItems: 'center',
        marginTop: '2.5rem',
        marginBottom: '2.5rem',
        gap: '1.5rem',
    },
    heroBar: {
        width: '90%',
        maxWidth: '900px',
        backgroundColor: '#E88D31',
        borderRadius: '0.5rem',
        display: 'flex',
        justifyContent: 'center',
        alignItems: 'center',
        minHeight: '60px',
        marginBottom: '1.5rem',
    },
    heroTitle: {
        color: '#fff',
        fontWeight: 700,
        fontSize: '2.5rem',
        letterSpacing: '0.5px',
        padding: '0.7rem 0',
        textAlign: 'center',
        width: '100%',
    },
    heroImageWrapper: {
        width: '90%',
        maxWidth: '900px',
        aspectRatio: '16/6',
        position: 'relative',
        borderRadius: '1rem',
        overflow: 'hidden',
        boxShadow: '0 4px 24px rgba(0,0,0,0.07)',
    },
    heroImage: {
        objectFit: 'cover',
    },
    section: {
        width: '90%',
        maxWidth: '900px',
        display: 'flex',
        flexDirection: 'column',
        gap: '1.5rem',
        alignItems: 'flex-start',
        margin: '0 auto',
    },
    sectionTitle: {
        fontSize: '2rem',
        fontWeight: 600,
        color: '#222',
        marginBottom: '0.2rem',
        textAlign: 'left',
    },
    sectionSubtitle: {
        fontSize: '1.1rem',
        color: '#757575',
        marginBottom: '0.5rem',
        textAlign: 'left',
    },
    infoCards: {
        display: 'flex',
        flexDirection: 'column',
        gap: '1rem',
        width: '100%',
    },
    infoCard: {
        border: '1px solid #E0E0E0',
        borderRadius: '0.7rem',
        padding: '1.2rem 1.5rem',
        background: '#fafbfc',
        boxShadow: '0 1px 4px rgba(0,0,0,0.03)',
    },
    infoCardTitle: {
        fontWeight: 600,
        fontSize: '1.1rem',
        marginBottom: '0.4rem',
        color: '#222',
    },
    infoCardText: {
        fontSize: '1rem',
        color: '#444',
        lineHeight: 1.6,
    },
    teamGrid: {
        display: 'grid',
        gridTemplateColumns: 'repeat(auto-fit, minmax(220px, 1fr))',
        gap: '1.5rem',
        width: '100%',
        marginTop: '1rem',
    },
    teamCard: {
        border: '1px solid #E0E0E0',
        borderRadius: '0.7rem',
        padding: '1.5rem 1rem',
        background: '#fff',
        display: 'flex',
        flexDirection: 'column',
        alignItems: 'center',
        gap: '0.6rem',
        boxShadow: '0 1px 4px rgba(0,0,0,0.03)',
    },
    avatarWrapper: {
        width: '3rem',
        height: '3rem',
        borderRadius: '50%',
        overflow: 'hidden',
        marginBottom: '0.5rem',
        background: '#f3f3f3',
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'center',
    },
    avatar: {
        width: '3rem',
        height: '3rem',
        objectFit: 'cover',
        borderRadius: '50%',
    },
    teamName: {
        fontWeight: 600,
        fontSize: '1.1rem',
        color: '#222',
    },
    teamRole: {
        color: '#757575',
        fontSize: '1rem',
    },
    teamExp: {
        color: '#B3B3B3',
        fontSize: '0.95rem',
    },
})