'use client'
import { makeStyles } from "@griffel/react"

export const useStyle = makeStyles({
    page: {
        display: 'flex',
        flexDirection: 'column',
        minHeight: '100vh',
        background: 'white',
    },
    body: {
        flex: 1,
        display: 'flex',
        flexDirection: 'column',
        alignItems: 'center',
        padding: '0 0 2.5rem 0',
        width: '100%',
        gap: '2rem',
    },
    title: {
        fontSize: '2.5rem',
        fontWeight: 700,
        textAlign: 'center',
        margin: '2rem 0 1.5rem 0',
        color: '#222',
    },
    visionCard: {
        width: '90%',
        maxWidth: '900px',
        background: '#fff',
        border: '1px solid #E0E0E0',
        borderRadius: '0.7rem',
        padding: '1.2rem 1.5rem',
        marginBottom: '1.5rem',
        boxShadow: '0 1px 4px rgba(0,0,0,0.03)',
    },
    visionTitle: {
        fontWeight: 600,
        fontSize: '1.1rem',
        marginBottom: '0.4rem',
        color: '#222',
    },
    visionDesc: {
        fontSize: '1rem',
        color: '#444',
        lineHeight: 1.6,
    },
    shopContent: {
        display: 'flex',
        flexDirection: 'row',
        width: '90%',
        maxWidth: '1200px',
        gap: '2rem',
        alignItems: 'flex-start',
        justifyContent: 'center',
    },
    cartSection: {
        minWidth: '260px',
        maxWidth: '300px',
        width: '22%',
        display: 'flex',
        flexDirection: 'column',
        gap: '1rem',
    },
    cartCard: {
        background: '#fff',
        border: '1px solid #E0E0E0',
        borderRadius: '0.7rem',
        padding: '1.5rem 1rem',
        boxShadow: '0 1px 4px rgba(0,0,0,0.03)',
        display: 'flex',
        flexDirection: 'column',
        gap: '1rem',
    },
    cartLabel: {
        fontWeight: 500,
        fontSize: '1rem',
        color: '#222',
        marginBottom: '0.2rem',
    },
    cartAmount: {
        fontWeight: 700,
        fontSize: '2rem',
        color: '#387A3D',
        marginBottom: '0.5rem',
    },
    cartCheckout: {
        backgroundColor: '#E88D31',
        color: 'white',
        fontWeight: 600,
        fontSize: '1.1rem',
        border: 'none',
        borderRadius: '0.4rem',
        padding: '0.7rem 0',
        cursor: 'pointer',
        marginBottom: '0.5rem',
        transition: 'background 0.2s',
        ':hover': {
            backgroundColor: '#d07b28',
        },
    },
    cartDonate: {
        backgroundColor: '#387A3D',
        color: 'white',
        fontWeight: 600,
        fontSize: '1.1rem',
        border: 'none',
        borderRadius: '0.4rem',
        padding: '0.7rem 0',
        cursor: 'pointer',
        marginBottom: '1rem',
        transition: 'background 0.2s',
        ':hover': {
            backgroundColor: '#2F5A2B',
        },
    },
    cartItemsHeader: {
        fontWeight: 500,
        fontSize: '1rem',
        color: '#222',
        marginBottom: '0.2rem',
    },
    cartItem: {
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'space-between',
        border: '1px solid #E0E0E0',
        borderRadius: '0.4rem',
        padding: '0.5rem 0.7rem',
        marginBottom: '0.5rem',
        background: '#fafbfc',
        gap: '0.5rem',
    },
    cartItemName: {
        fontWeight: 600,
        fontSize: '1rem',
        color: '#222',
    },
    cartItemDesc: {
        fontSize: '0.95rem',
        color: '#757575',
    },
    cartItemQty: {
        display: 'flex',
        alignItems: 'center',
        gap: '0.3rem',
    },
    qtyBtn: {
        background: '#f3f3f3',
        border: 'none',
        borderRadius: '0.3rem',
        width: '1.5rem',
        height: '1.5rem',
        cursor: 'pointer',
        fontWeight: 700,
        fontSize: '1rem',
        color: '#222',
        ':hover': {
            background: '#e0e0e0',
        },
    },
    cartItemRemove: {
        background: 'none',
        border: 'none',
        color: '#B3B3B3',
        fontSize: '1.2rem',
        cursor: 'pointer',
        marginLeft: '0.5rem',
        ':hover': {
            color: '#E88D31',
        },
    },
    productsSection: {
        flex: 1,
        display: 'flex',
        flexDirection: 'column',
        gap: '1.5rem',
    },
    productsHeader: {
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'space-between',
        gap: '1rem',
        marginBottom: '1rem',
    },
    searchInput: {
        border: '1px solid #E0E0E0',
        borderRadius: '0.4rem',
        padding: '0.6rem 1rem',
        fontSize: '1rem',
        width: '220px',
        outline: 'none',
        marginRight: '1rem',
        ':focus': {
            border: '1.5px solid #E88D31',
        },
    },
    filterGroup: {
        display: 'flex',
        gap: '0.5rem',
    },
    filterBtn: {
        background: '#f3f3f3',
        border: 'none',
        borderRadius: '0.4rem',
        padding: '0.5rem 1rem',
        fontSize: '1rem',
        color: '#222',
        cursor: 'pointer',
        fontWeight: 500,
        ':hover': {
            background: '#e0e0e0',
        },
    },
    filterBtnActive: {
        background: '#222',
        color: 'white',
        border: 'none',
        borderRadius: '0.4rem',
        padding: '0.5rem 1rem',
        fontSize: '1rem',
        fontWeight: 600,
        cursor: 'pointer',
    },
    productsGrid: {
        display: 'grid',
        gridTemplateColumns: 'repeat(auto-fit, minmax(220px, 1fr))',
        gap: '1.5rem',
        width: '100%',
        marginTop: '1rem',
    },
    productCard: {
        border: '1px solid #E0E0E0',
        borderRadius: '0.7rem',
        padding: '1rem',
        background: '#fff',
        display: 'flex',
        flexDirection: 'column',
        alignItems: 'center',
        gap: '0.5rem',
        boxShadow: '0 1px 4px rgba(0,0,0,0.03)',
        position: 'relative',
    },
    productImg: {
        width: '100%',
        height: '140px',
        objectFit: 'cover',
        borderRadius: '0.5rem',
        marginBottom: '0.5rem',
    },
    productName: {
        fontWeight: 600,
        fontSize: '1.1rem',
        color: '#222',
        textAlign: 'center',
    },
    productPrice: {
        color: '#387A3D',
        fontWeight: 700,
        fontSize: '1rem',
        marginBottom: '0.2rem',
    },
    productDesc: {
        color: '#757575',
        fontSize: '0.98rem',
        textAlign: 'center',
        marginBottom: '0.5rem',
    },
    addToCartBtn: {
        position: 'absolute',
        bottom: '1rem',
        right: '1rem',
        background: '#E88D31',
        color: 'white',
        border: 'none',
        borderRadius: '50%',
        width: '2.2rem',
        height: '2.2rem',
        fontSize: '1.2rem',
        cursor: 'pointer',
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'center',
        ':hover': {
            background: '#d07b28',
        },
    },
})